export const students = [
  "Aadeesh Maurya",
  "Ankit Jafee",
  "Aayush",
  "Adarsh Mondal",
  "Ali Hamid",
  "Aman Deep Yadav",
  "Anant Kaser",
  "Aniket Kumar Agrahar",
  "Anshika Rai",
  "Anshul Chandra",
  "Arpit Tripathi",
  "Arya Singh",
  "Ayan",
  "Ayush Kesharwani",
  "Bhanu Pratap Singh",
  "Divyansh Jaiswal",
  "Ekta Khan",
  "Faizullah",
  "Fizan Khan",
  "Fizan Anees",
  "Hanza Ansari",
  "Harsh Gupta",
  "Harsh Mishra",
  "Hritik Singh",
  "Indresh Singh",
  "Insha",
  "Jahid Abdullah",
  "Kishan Kumar",
  "Krishna",
  "Mohammad Saker",
  "Mohd Arshad",
  "Naman Soni",
  "Om Prakash Sahu",
  "Om Vikram Singh (Dimy)",
  "Om Jaiswal",
  "Piyush Kumar Sharma",
  "Pooja Kumari",
  "Prashant Shukla",
  "Priyanshi Singh",
  "Pushpraj",
  "Ram Krishna Pandey",
  "Rishant Singh",
  "Rishi Dubey",
  "Satyansh Srivastava",
  "Sayon Manna",
  "Shiva Khan",
  "Shiva Tiwari",
  "Shivam",
  "Shivam Singh",
  "Shivam Yadav",
  "Shreey Kesharwani",
  "Shreya Gupta",
  "Shyama Kasera",
  "Smriti Prajapati",
  "Soniya Mondal",
  "Sparsh Gupta",
  "Tanvi Gupta",
  "Tanu Shree Yadav",
  "Utkarsh Dubey",
  "Vaidehi Singh",
  "Vaishnavi Singh",
  "Vinayak Dubey",
  "Vishwas Pandey",
  "Yatharth Upadhyay",
  "Yawar Ahmad",
  "Zoya Khan",
];

console.log(students.length);
